# override permissions for any command
permissions:
  liveinteraction:
    whitelist: ${ [ ROLES.PILLAR_STAFF, ...getValuesRecursive(ROLES.ADMIN) ] }

  livecommand:
    whitelist: ${ [ ROLES.PILLAR_STAFF, ...getValuesRecursive(ROLES.ADMIN) ] }

activityStatus:
  message: with DEEZ NUTZ
  type: PLAYING
